### PR TITLE
[NOT FOR MERGE]add fields for easier validation

### PR DESCRIPTION
**Pull request by sayan-rudder**
- also has the changes for samesite=Lax for cookies.

---
This change is [Reviewable](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/48)

### CODE REVIEW

**Comment by shubhamrathioncehub** [comment]
Hi, my team is waiting for this PR to be merged.

**Comment by sayan-rudder** [comment]
Hi @shubhamrathioncehub 
most changes in this PR are in master now, 
can you let us know what all changes do you need ?

**Comment by shubhamrathioncehub** [comment]
@sayan-rudder I am mostly interested in Lax cookie change, can you please let me know if it is merged in master already?

**Comment by sayan-rudder** [comment]
yes, it is merged. You can use this distribution: https://cdn.rudderlabs.com/v1/rudder-analytics.min.js.
@shubhamrathioncehub

**Comment by sayan-rudder** [comment]
merged into master by cherry-picking
closing this

**Pull request closed without merging**
