### PR TITLE
Chrome Extension docs cleanup and added type

### PR DESCRIPTION
**Pull request by mcleonard**
## Description of the change

This adds a few commits to clean up the new chrome extension feature:
- a couple documentation improvements
- adds an extra type declaration to work with our (Bardeen's) code

## Type of change
- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

- - -
This change is [Reviewable](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/694)

### CODE REVIEW

**Comment by mcleonard** [comment]
After making this PR, I realized I made a change in the Node module's `package.json` file.
This part doesn't seem to work:
```
"exports": {
    ".": {
      "service-worker": "./service-worker/index.es.js"
    }
  },
```

I don't think "service-worker" is a valid conditional. Setting this to "browser" works.

What I did is set it to
```
"exports": {
    "service-worker": "./service-worker/index.es.js"
  },
```

then in my code
```
import { Analytics } from "rudder-js-sdk/service-worker"
```

**Comment by mcleonard** [comment]
Something I haven't figured out yet is how to get TypeScript to play nicely. 

Importing with  `import { Analytics } from "rudder-sdk-js/service-worker";` gives me a TypeScript error
```
Module '"rudder-sdk-js/service-worker"' has no exported member 'Analytics'. Did you mean to use 'import Analytics from "rudder-sdk-js/service-worker"' instead?
```
but it builds the extension and I’m sending data through RudderStack. Very happy it works! But I don’t like the TypeScript Error.

When I try `import Analytics from "rudder-sdk-js/service-worker"` the TypeScript error goes away and I have all the type information. But I have a Webpack warning
```
export 'default' (imported as 'Analytics') was not found in 'rudder-sdk-js/service-worker'
```
and the SDK fails to load correctly.

Haven't figured out a solution to this yet. I'm not too knowledgeable about TypeScript and Webpack things.

**Comment by bardisg** [comment]
Hello @mcleonard ,

Thank you for your contributions, he have identified the issues with package export and exported types and we are in the process to rectify them. 

We should have a new version out soon that rectifies the issue and you will not have an issue importing in a typescript project.

Will update here as soon as a new release is out.

**Comment by mcleonard** [comment]
I think this PR can be closed as all (or most) of the changes were addressed in the last commit: https://github.com/rudderlabs/rudder-sdk-js/commit/1883367cd771de3c17bb8da30e3d6b5b6f9c4d63

**Comment by bardisg** [comment]
New release v2.18.0 contains relevant fix

**Pull request closed without merging**
