### PR TITLE
feat(new integration): onboarding june device mode destination v1.1

### PR DESCRIPTION
**Pull request by Gauravudia**
## Description of the change

> Onboarding June device mode destination

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

- - -
This change is [Reviewable](https://reviewable.io/reviews/rudderlabs/rudder-sdk-js/673)

### CODE REVIEW

**Review by MoumitaM — CHANGES_REQUESTED** [review]
In order for logger module to work add the below code in browser.js.
1. Add **analytics** in the constructor
`constructor(config, analytics) {`
2. Add the below code in the constructor.
    `if (analytics.logLevel) {
      logger.setLogLevel(analytics.logLevel);
    }`

**Comment by Gauravudia** [comment]
> In order for logger module to work add the below code in browser.js.
> 
> 1. Add **analytics** in the constructor
>    `constructor(config, analytics) {`
> 2. Add the below code in the constructor.
>    `if (analytics.logLevel) { logger.setLogLevel(analytics.logLevel); }`

Updated in production-staging. Do I need to update these changes in v1-staging also??

**Comment by saikumarrs** [comment]
> > In order for logger module to work add the below code in browser.js.
> > 
> > 1. Add **analytics** in the constructor
> >    `constructor(config, analytics) {`
> > 2. Add the below code in the constructor.
> >    `if (analytics.logLevel) { logger.setLogLevel(analytics.logLevel); }`
> 
> Updated in production-staging. Do I need to update these changes in v1-staging also??

It's better to address this in the `v1-staging` branch and let them automatically flow into v1.1 branches.

**Comment by Gauravudia** [comment]
> > > In order for logger module to work add the below code in browser.js.
> > > 
> > > 1. Add **analytics** in the constructor
> > >    `constructor(config, analytics) {`
> > > 2. Add the below code in the constructor.
> > >    `if (analytics.logLevel) { logger.setLogLevel(analytics.logLevel); }`
> > 
> > 
> > Updated in production-staging. Do I need to update these changes in v1-staging also??
> 
> It's better to address this in the `v1-staging` branch and let them automatically flow into v1.1 branches.

raised the PR for v1-staging 
https://github.com/rudderlabs/rudder-sdk-js/pull/675#pullrequestreview-1127794464

**Review by shrouti1507 — APPROVED** [review]

**Review by MoumitaM — APPROVED** [review]

**Review by shrouti1507 — APPROVED** [review]

**Pull request merged**
