### PR TITLE
fix: mixpanel cookie persistence storage

### PR DESCRIPTION
**Pull request by Gauravudia**
## PR Description

Resolves INT-186

`Issue`:
The current implementation incorrectly assigns the persistence type (config.persistence) to options.persistence_name, which only adds a suffix to the cookie without controlling the persistence storage as intended.

`Solution`:
This PR introduces the new parameter options.persistence to effectively manage the persistence storage. 

## Notion ticket

[Ticket link](https://www.notion.so/rudderstacks/Mixpanel-persistenceType-fix-2de59be6ea784ecca46aa31dd7eb0966)

## Screenshots

Please add screenshots for any new features or UI bug fixes for the following browsers -

- Chrome
  >
- Firefox
  >
- Safari
  >

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

### CODE REVIEW

**Review by ItsSudip — DISMISSED** [review]

**Review by ItsSudip — APPROVED** [review]

**Review by ItsSudip — APPROVED** [review]

**Review by utsabc — CHANGES_REQUESTED** [review]
Add Test cases for this init change

**Comment by Gauravudia** [comment]
> Add Test cases for this init change

Added the test cases

**Review by utsabc — APPROVED** [review]

**Comment by Gauravudia** [comment]
Raising this as hotfix

**Comment by Gauravudia** [comment]
Raising this as hotfix

**Pull request closed without merging**
